[package]
name = "stardust_sdvx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stardust_common = { path = "../stardust_common" }
thiserror = "1.0"
