[package]
name = "stardust_world"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
puffin = "0.13.3"
itertools = "0.10"
foxtail = { path = "../../foxtail/foxtail" }

stardust_common = { path = "../stardust_common" }
stardust_sdvx = { path = "../stardust_sdvx" }
