[package]
name = "stardust_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
foxtail = { path = "../../foxtail/foxtail" }
egui = "0.19.0"

stardust_common = { path = "../stardust_common" }
stardust_world = { path = "../stardust_world" }
