[package]
name = "stardust"
version = "0.1.0"
edition = "2021"

[dependencies]
sensible-env-logger = { version = "0.3.1", features = ["local-time"] }
log = "0.4"
winit = "0.27"
raw-gl-context = "0.1.2"
glow = "0.11.2"
