[package]
name = "stardust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26"
sensible-env-logger = { version = "0.3.1", features = ["local-time"] }
log = "0.4"
wgpu = "0.13"
